service: burst-compute-example

plugins:
  - serverless-bundle

custom:
  version: 1.0.0
  debug: true
  maxParallelism: 3000
  burstComputeStage: ${env:BURST_COMPUTE_STAGE, self:provider.stage}
  dispatchFunction: ${cf:burst-compute-${self:custom.burstComputeStage}.DispatchLambdaFunction}
  tasksTable: ${cf:burst-compute-${self:custom.burstComputeStage}.TasksTable}
  outputBucket: ${env:BUCKET, 'burst-compute-example-${self:custom.burstComputeStage}'}
  outputPrefix: ${env:PREFIX, 'fractal'}
  # Work around for native compilation
  # from https://github.com/lovell/sharp/issues/2230#issuecomment-698653336
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - npm install --arch=x64 --platform=linux sharp
        
provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::${self:custom.outputBucket}/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 
        - "arn:aws:lambda:${self:provider.region}:*:function:${self:custom.dispatchFunction}"
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tasksTable}"

functions:

  launcher:
    handler: launcher.handler
    memorySize: 128
    timeout: 10
    environment:
      DEBUG: ${self:custom.debug}
      DISPATCH_FUNCTION_ARN: ${self:custom.dispatchFunction}
      WORKER_FUNCTION_ARN: !Ref WorkerLambdaFunction
      COMBINER_FUNCTION_ARN: !Ref CombinerLambdaFunction
      MAX_PARALLELISM: ${self:custom.maxParallelism}

  worker:
    handler: worker.handler
    memorySize: 128
    timeout: 30
    environment:
      DEBUG: ${self:custom.debug}
      OUTPUT_BUCKET: ${self:custom.outputBucket}
      OUTPUT_PREFIX: ${self:custom.outputPrefix}

  combiner:
    handler: combiner.handler
    memorySize: 512
    timeout: 900
    environment:
      DEBUG: ${self:custom.debug}
      OUTPUT_BUCKET: ${self:custom.outputBucket}
      OUTPUT_PREFIX: ${self:custom.outputPrefix}
      DELETE_TILES: true

  fractalLocalDisk:
    handler: worker.fractalLocalDisk
    memorySize: 128
    timeout: 30

  fractalS3:
    handler: worker.fractalS3
    memorySize: 128
    timeout: 30
    environment:
      OUTPUT_BUCKET: ${self:custom.outputBucket}
      OUTPUT_PREFIX: ${self:custom.outputPrefix}

